name: tudat-multidoc
channels:
  - conda-forge
  - tudat-team
dependencies:
  # All standard tudat-bundle deps are needed for sphinx-documentation for tudatpy.
  - eigen
  - boost-cpp
  - tudat-resources
  - sofa-cmake
  - cspice-cmake
  - nrlmsise-00
  - python == 3.9
  - pybind11
  - pybind11-abi
  - numpy
  - pandas # for tudat.io
  - pytest
  - matplotlib # for tudat.plotting
  # - basemap # for tudat.plotting
  # - basemap-data-hires # for tudat.plotting
  # Other doc related
  - jinja2
  - pyyaml
  - pydantic == 1.10.9
  - numpydoc
  - doxygen # for cpp api
  - pip
  - pip:
     - nbsphinx
     - sphinxcontrib-napoleon
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex
     - furo
     - sphinx_copybutton 
